-- This file is for use with Corona Game Edition
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

module(...)

function physicsData(scale)
	local physics = { data =
	{ 
		
		["sprocket_1"] = {
			
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   10.5, 233  ,  -16.5, 190  ,  59, 182.5  ,  52, 224.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   183.5, 141  ,  128.5, 133  ,  176.5, 70  ,  204, 102.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   224, 63.5  ,  176.5, 70  ,  198, -3.5  ,  233, 21.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   198, -3.5  ,  176, -76.5  ,  218.5, -69  ,  230, -28.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -93, 164.5  ,  -16.5, 190  ,  -49.5, 227  ,  -91, 213.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   203, -109.5  ,  176, -76.5  ,  136, -144.5  ,  178.5, -152  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -189, 37.5  ,  -155, 109.5  ,  -204, 108.5  ,  -219.5, 67  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   67, -179.5  ,  -155, 109.5  ,  -13, -193.5  ,  15.5, -235  ,  57.5, -228  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -13, -193.5  ,  -96, -175.5  ,  -85.5, -221  ,  -43.5, -233  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   136, -144.5  ,  67, -179.5  ,  109.5, -204  ,  145, -179.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -153, -127.5  ,  -189.5, -46  ,  -220, -88.5  ,  -199.5, -128  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -145, -188.5  ,  -134, -197.5  ,  -96, -175.5  ,  -153, -127.5  ,  -168, -162.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   59, 182.5  ,  128.5, 133  ,  136, 187.5  ,  99, 209.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -189.5, -46  ,  -189, 37.5  ,  -234, 16.5  ,  -235, -25.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -155, 109.5  ,  -93, 164.5  ,  -138.5, 186  ,  -171, 158.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   176.5, 70  ,  128.5, 133  ,  -93, 164.5  ,  -155, 109.5  ,  67, -179.5  ,  136, -144.5  ,  176, -76.5  ,  198, -3.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -16.5, 190  ,  -93, 164.5  ,  128.5, 133  ,  59, 182.5  }
				}  ,
				{
					density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -13, -193.5  ,  -155, 109.5  ,  -189, 37.5  ,  -189.5, -46  ,  -153, -127.5  ,  -96, -175.5  }
				}  
		}
		
	} }

	-- apply scale factor
	local s = scale or 1.0
	for bi,body in pairs(physics.data) do
		for fi,fixture in ipairs(body) do
			for ci,coordinate in ipairs(fixture.shape) do
				fixture.shape[ci] = s * coordinate
			end
		end
	end
	
	function physics:get(name)
		return unpack(self.data[name])
	end
	
	return physics;
end


